### ISSUE TITLE
someblocks not working.

### ISSUE THREAD

**Issue by ghost** [MadcowOG/dwl-bar#1]
someblocks is not working.

**Comment by AliJM1** [comment]
I am not sure what your problem is, but it may be solved by running someblocks with -s option. If you want to run someblocks with dwl-bar you can do it like below:
`someblocks -s /run/user/1000/dwl-bar-0`
with -s option you can specify the location of the file that dwl-bar reads from, in this case, the location is "/run/user/1000/dwl-bar-0"
You have to specify the -s because someblocks by default sets this location to "$XDG_RUNTIME_DIR/somebar-0" which in my case is "/run/user/1000/somebar-0", but because we are not using somebar we change that location.
I think this will solve your problem.

**Comment by ghost** [comment]
You are right , My bad.  thanks for helping me out.
